#!/bin/bash
if [[ $1 == -p ]]; then
    cd client
    npm run build
    npm run less
    cd ../server
    npm run build
else
    cd client
    npm run build:dev
    npm run less:dev
    cd ../server
    npm run build
fi
