#! /bin/bash

docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
docker build -t scoringguide .
docker tag scoringguide:latest osucass/scoringguide:$BRANCH
docker push osucass/scoringguide:$BRANCH