#!/bin/bash
if [[ $# -eq  1 ]]; then
    if [ $1 == -u ]; then
        echo "updating tests in client/..."
        cd client/
        npm test -u
        echo "updating tests in server/..."
        cd ../server
        npm test -u
    elif [ $1 == -c ]; then
        echo "running tests in server/ with coverage..."
        cd client/
        npm run coverage
        echo "running tests in server/ with coverage..."
        cd ../server
        npm test --coverage
    else
        echo "./test {-u|-c} => update | coverage"
        exit 1
    fi
elif [[ $# -eq  0 ]]; then
    echo "running tests in client/..."
    cd client/
    npm test
    echo "running tests in server/..."
    cd ../server
    npm test  
fi
